// <auto-generated />
using System;
using System.Collections.Generic;
using MMS.Adapters.PostgreSQL.Data;
using MMS.Application.Models.SQL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MMS.Adapters.PostgreSQL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250901111135_UpdateMachineIndexe")]
    partial class UpdateMachineIndexe
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CustomerReportSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValue(new Guid("84d10093-5889-4fde-8c70-7abedb91eea9"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<string>>("Email")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsCustomReport")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string[]>("MachineIds")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("ReportName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("ReportPeriodEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ReportPeriodStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string[]>("ReportType")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<string[]>("WeekDays")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("CustomerReportSetting");
                });

            modelBuilder.Entity("MMS.Application.Models.SQL.ApplicationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValue(new Guid("80546439-88e4-4fd4-8bcd-23abb332455d"));

                    b.Property<string>("ApiRequest")
                        .HasColumnType("jsonb");

                    b.Property<string>("ApiResponse")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Exception")
                        .HasColumnType("text");

                    b.Property<string>("Level")
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("ApplicationLogs");
                });

            modelBuilder.Entity("MMS.Application.Models.SQL.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValue(new Guid("28e95ce3-2cc2-4247-82be-52fae3d9f394"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ImageUrls")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("PhoneCountryCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<Shift>>("Shifts")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            City = "Karachi",
                            Country = "Pakistan",
                            Email = "customer1@example.com",
                            ImageUrls = "https://apcstorageaccount.blob.core.windows.net/mms-container/2025_06_19_pexels-pixabay-69932.jpg",
                            Name = "Customer 1",
                            PhoneCountryCode = "+92",
                            PhoneNumber = "3001234561",
                            PostalCode = "74200",
                            Region = "Sindh",
                            Shifts = new List<Shift>(),
                            Status = 0,
                            Street = "1st Avenue",
                            TimeZone = "Asia/Karachi"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111112"),
                            City = "Lahore",
                            Country = "Pakistan",
                            Email = "customer2@example.com",
                            ImageUrls = "https://apcstorageaccount.blob.core.windows.net/mms-container/2025_06_19_pexels-pixabay-69932.jpg",
                            Name = "Customer 2",
                            PhoneCountryCode = "+92",
                            PhoneNumber = "3001234562",
                            PostalCode = "54000",
                            Region = "Punjab",
                            Shifts = new List<Shift>(),
                            Status = 0,
                            Street = "2nd Avenue",
                            TimeZone = "Asia/Karachi"
                        });
                });

            modelBuilder.Entity("MMS.Application.Models.SQL.CustomerBillingAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValue(new Guid("5b1bda0a-f247-4015-8759-1f0f955027f2"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("street")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("CustomerBillingAddresses", (string)null);
                });

            modelBuilder.Entity("MMS.Application.Models.SQL.CustomerDashboard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValue(new Guid("c9434249-083e-45ef-b3ce-4fc337dca0bf"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<Dictionary<string, object>>("Layout")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int?>("RefreshInterval")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Theme")
                        .HasMaxLength(200)
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("CustomerDashboards");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c1277139-895e-4efa-a9c0-c544406a2ce1"),
                            CustomerId = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsDefault = false,
                            Layout = new Dictionary<string, object>(),
                            Name = "Dashboard 1",
                            RefreshInterval = 60,
                            Status = 0,
                            Theme = 1
                        },
                        new
                        {
                            Id = new Guid("c1277139-895e-4efa-a9c0-c544406a2ce2"),
                            CustomerId = new Guid("11111111-1111-1111-1111-111111111112"),
                            IsDefault = false,
                            Layout = new Dictionary<string, object>(),
                            Name = "Dashboard 2",
                            RefreshInterval = 60,
                            Status = 0,
                            Theme = 1
                        });
                });

            modelBuilder.Entity("MMS.Application.Models.SQL.CustomerReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValue(new Guid("35e40e74-ffe2-4abf-aa63-3b1903a8f2bc"));

                    b.Property<string>("BlobLink")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerReportSettingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("Format")
                        .HasColumnType("integer");

                    b.Property<DateTime>("GeneratedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsSent")
                        .HasColumnType("boolean");

                    b.Property<string>("ReportName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("CustomerReportSettingId");

                    b.ToTable("CustomerReports");
                });

            modelBuilder.Entity("MMS.Application.Models.SQL.CustomerSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValue(new Guid("8bd0bae0-c32e-4ba2-9e04-b5883144ca32"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("RenewalType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("CustomerSubscriptions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("88888888-1111-1111-1111-111111111111"),
                            CustomerId = new Guid("11111111-1111-1111-1111-111111111111"),
                            EndDate = new DateTime(2024, 1, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            InvoiceId = new Guid("99999999-2222-2222-2222-222222222222"),
                            IsActive = true,
                            RenewalType = 2,
                            StartDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Active",
                            SubscriptionId = new Guid("45b429a4-f21b-4be4-981b-a4ecee7244b1")
                        });
                });

            modelBuilder.Entity("MMS.Application.Models.SQL.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValue(new Guid("b6deb981-48da-43ce-ad1a-7cc1f999c3d9"));

                    b.Property<decimal>("Amout")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("BillingAdressId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerSubscriptionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Invoicenumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("Payment")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentGatewayTrxId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Paymentmethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Tax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Invoices", (string)null);
                });

            modelBuilder.Entity("MMS.Application.Models.SQL.Machine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValue(new Guid("677bf3db-26d0-4fa6-9280-e79e892398d3"));

                    b.Property<int>("CommunicationProtocol")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<DateTime?>("InstallationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("MachineModel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("MachineType")
                        .HasColumnType("integer");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("text");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("idx_machine_customerid");

                    b.HasIndex("Id")
                        .HasDatabaseName("idx_machine_id");

                    b.ToTable("Machines");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b9cdaa9c-b1b0-48ce-af8e-fda9677a8d91"),
                            CommunicationProtocol = 2,
                            CustomerId = new Guid("11111111-1111-1111-1111-111111111111"),
                            InstallationDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Location = "Location 1",
                            MachineModel = "Model X",
                            MachineName = "Machine 1",
                            MachineType = 2,
                            Manufacturer = "Manufacturer A",
                            SerialNumber = "SN001"
                        },
                        new
                        {
                            Id = new Guid("b9cdaa9c-b1b0-48ce-af8e-fda9677a8d92"),
                            CommunicationProtocol = 2,
                            CustomerId = new Guid("11111111-1111-1111-1111-111111111112"),
                            InstallationDate = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Location = "Location 2",
                            MachineModel = "Model X",
                            MachineName = "Machine 2",
                            MachineType = 3,
                            Manufacturer = "Manufacturer B",
                            SerialNumber = "SN002"
                        });
                });

            modelBuilder.Entity("MMS.Application.Models.SQL.MachineMaintenanceTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValue(new Guid("74fd1459-6dac-4d70-b2ee-a0e7994cb2e8"));

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsFinished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("MachineId")
                        .HasColumnType("uuid");

                    b.Property<string>("MaintenanceTaskName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.ToTable("MachineMaintenances");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaa1-1111-1111-1111-111111111111"),
                            Category = 6,
                            IsFinished = false,
                            MachineId = new Guid("b9cdaa9c-b1b0-48ce-af8e-fda9677a8d91"),
                            MaintenanceTaskName = "Task 1",
                            StartTime = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("MMS.Application.Models.SQL.MachineSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValue(new Guid("4bf10851-6a53-4760-acaa-c2c6443218dc"));

                    b.Property<List<Alert>>("Alerts")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("AutomaticPartsCounter")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("CycleStartInterlock")
                        .HasColumnType("boolean");

                    b.Property<bool>("CycleStop")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<string>>("DownTimeReasons")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<Guid>("MachineId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly?>("MaxCycleDuration")
                        .HasColumnType("time without time zone");

                    b.Property<decimal?>("MaxFeedrate")
                        .HasColumnType("numeric");

                    b.Property<int?>("MaxSpindleSpeed")
                        .HasColumnType("integer");

                    b.Property<int?>("PartsPerCycle")
                        .HasColumnType("integer");

                    b.Property<bool>("SoundAlert")
                        .HasColumnType("boolean");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<TimeOnly?>("StopInterval")
                        .HasColumnType("time without time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MachineId")
                        .IsUnique();

                    b.ToTable("MachineSettings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("99999999-1111-1111-1111-111111111111"),
                            Alerts = new List<Alert>(),
                            AutomaticPartsCounter = false,
                            CycleStartInterlock = false,
                            CycleStop = false,
                            DownTimeReasons = new List<string> { "Power Failure" },
                            MachineId = new Guid("b9cdaa9c-b1b0-48ce-af8e-fda9677a8d91"),
                            MaxCycleDuration = new TimeOnly(0, 0, 0),
                            SoundAlert = false,
                            Status = 0,
                            StopInterval = new TimeOnly(0, 0, 0)
                        });
                });

            modelBuilder.Entity("MMS.Application.Models.SQL.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValue(new Guid("44ed3c08-996d-4dbc-92f8-8d019d39068e"));

                    b.Property<string>("ActionId")
                        .HasColumnType("text");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Dictionary<string, object>>("DataPayload")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ReadStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Topic")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int?>("click_action")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("MMS.Application.Models.SQL.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValue(new Guid("e540db55-67a8-4640-8e14-84e067e0e534"));

                    b.Property<int>("BillingCycle")
                        .HasMaxLength(50)
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<Dictionary<string, object>>("Features")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Subscriptions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("45b429a4-f21b-4be4-981b-a4ecee7244b1"),
                            BillingCycle = 0,
                            Currency = "USD",
                            Features = new Dictionary<string, object>(),
                            Name = "Plan 1",
                            Price = 9.99m,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("45b429a4-f21b-4be4-981b-a4ecee7244b2"),
                            BillingCycle = 0,
                            Currency = "USD",
                            Features = new Dictionary<string, object>(),
                            Name = "Plan 2",
                            Price = 19.99m,
                            Status = 0
                        });
                });


            modelBuilder.Entity("MMS.Application.Models.SQL.UserMachine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValue(new Guid("9ae6f68c-5489-472e-a0a2-3a54072b770f"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MachineId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.HasIndex("UserId", "MachineId")
                        .IsUnique();

                    b.ToTable("UserMachines");
                });

            modelBuilder.Entity("MMS.Application.Models.SQL.Widget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValue(new Guid("e16b7663-74d0-4247-b870-f98c0dae56d2"));

                    b.Property<Dictionary<string, object>>("Config")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DashboardId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("SourceType")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("WidgetType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DashboardId");

                    b.ToTable("Widgets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ddddddd1-1111-1111-1111-111111111111"),
                            Config = new Dictionary<string, object>(),
                            DashboardId = new Guid("c1277139-895e-4efa-a9c0-c544406a2ce1"),
                            SourceType = 0,
                            WidgetType = 3
                        });
                });

            modelBuilder.Entity("CustomerReportSetting", b =>
                {
                    b.HasOne("MMS.Application.Models.SQL.Customer", "Customer")
                        .WithMany("CustomerReportSettings")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("MMS.Application.Models.SQL.CustomerDashboard", b =>
                {
                    b.HasOne("MMS.Application.Models.SQL.Customer", "Customer")
                        .WithOne("CustomerDashboard")
                        .HasForeignKey("MMS.Application.Models.SQL.CustomerDashboard", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("MMS.Application.Models.SQL.CustomerReport", b =>
                {
                    b.HasOne("MMS.Application.Models.SQL.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CustomerReportSetting", "CustomerReportSetting")
                        .WithMany()
                        .HasForeignKey("CustomerReportSettingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("CustomerReportSetting");
                });

            modelBuilder.Entity("MMS.Application.Models.SQL.Machine", b =>
                {
                    b.HasOne("MMS.Application.Models.SQL.Customer", "Customer")
                        .WithMany("Machine")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("MMS.Application.Models.SQL.MachineMaintenanceTask", b =>
                {
                    b.HasOne("MMS.Application.Models.SQL.Machine", "Machine")
                        .WithMany("MachineMaintenanceTask")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("MMS.Application.Models.SQL.MachineSetting", b =>
                {
                    b.HasOne("MMS.Application.Models.SQL.Machine", "Machine")
                        .WithOne("MachineSetting")
                        .HasForeignKey("MMS.Application.Models.SQL.MachineSetting", "MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("MMS.Application.Models.SQL.UserMachine", b =>
                {
                    b.HasOne("MMS.Application.Models.SQL.Machine", "Machine")
                        .WithMany("UserMachine")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("MMS.Application.Models.SQL.Widget", b =>
                {
                    b.HasOne("MMS.Application.Models.SQL.CustomerDashboard", "CustomerDashboard")
                        .WithMany("Widget")
                        .HasForeignKey("DashboardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerDashboard");
                });

            modelBuilder.Entity("MMS.Application.Models.SQL.Customer", b =>
                {
                    b.Navigation("CustomerDashboard")
                        .IsRequired();

                    b.Navigation("CustomerReportSettings");

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("MMS.Application.Models.SQL.CustomerDashboard", b =>
                {
                    b.Navigation("Widget");
                });

            modelBuilder.Entity("MMS.Application.Models.SQL.Machine", b =>
                {
                    b.Navigation("MachineMaintenanceTask");

                    b.Navigation("MachineSetting")
                        .IsRequired();

                    b.Navigation("UserMachine");
                });
#pragma warning restore 612, 618
        }
    }
}
